
def follows():
    follow=[[]]
    follow.append(['a','g','h'])
    follow.append(['a','g','h'])
    follow.append(['a','q','r','b','c','e','g','h','i','l','m','o'])
    follow.append(['a','g','h'])
    follow.append(['b'])
    follow.append(['j'])
    follow.append(['a','b','c','e','g','h','i','l','m','o','p','q','r'])
    follow.append(['j','k'])
    follow.append(['j','k'])
    follow.append(['q','r','b','c','e','g','h','i','l','m','o'])
    follow.append(['q','r','b','c','e','i','l','m','o'])
    follow.append(['p', 'q', 'r', 'b', 'c', 'e', 'i', 'l', 'm', 'o'])
    follow.append(['p', 'q', 'r', 'b', 'c', 'e', 'i', 'l', 'm', 'o'])
    follow.append(['p', 'q', 'r', 'b', 'c', 'e', 'i', 'l', 'm', 'o'])
    follow.append(['p', 'q', 'r', 'b', 'c', 'e', 'i', 'l', 'm', 'o'])
    follow.append(['p', 'q', 'r', 'b', 'c', 'e', 'i', 'l', 'm', 'o'])
    follow.append(['c','f','j','k'])
    follow.append(['s','c','t','u','f','w','x','y','j','k'])
    follow.append(['z'])
    follow.append(['c','f','j','k'])
    follow.append(['c','t','u','f','w','x','j','k'])
    follow.append(['b','e','i'])
    follow.append(['b','e','i'])
    follow.append(['c','t','u','f','w','x','y','j','k'])
    follow.append(['c','t','u','f','w','x','y','j','k'])
    follow.append(['c','t','u','f','w','x','y','j','k'])
    follow.append(['j'])
    follow.append(['j','k'])
    follow.remove([])
    return follow
