
def grammar():
    grammar=[[]]

    grammar.append(['Ś', 'S'])
    grammar.append(['S', 'A', 'a'])
    grammar.append(['A', 'A', 'B'])
    grammar.append(['A', 'B'])
    grammar.append(['B', 'C'])
    grammar.append(['B', 'D'])
    grammar.append(['C','E','b','c'])
    grammar.append(['C','E','b','d','e','f','c'])
    grammar.append(['E', 'g'])
    grammar.append(['E','h'])
    grammar.append(['D','E','b','i','F','j','G'])
    grammar.append(['F','H'])
    grammar.append(['F','h'])
    grammar.append(['H','H','k','I'])
    grammar.append(['H','I'])
    grammar.append(['I','E','b'])
    grammar.append(['I','E','b','d','f'])
    grammar.append(['G','l','J','K','m'])
    grammar.append(['J','J','C'])
    grammar.append(['J',''])
    grammar.append(['K','K','L'])
    grammar.append(['K',''])
    grammar.append(['L','M'])
    grammar.append(['L','G'])
    grammar.append(['L','N'])
    grammar.append(['L','O'])
    grammar.append(['L','P'])
    grammar.append(['M','Q','c'])
    grammar.append(['M','c'])
    grammar.append(['N','o','i','Q','j','L','p','L'])
    grammar.append(['O','q','i','Q','j','L'])
    grammar.append(['P','r','c'])
    grammar.append(['P','r','Q','c'])
    grammar.append(['Q','R','s','Q'])
    grammar.append(['Q','T'])
    grammar.append(['R','b'])
    grammar.append(['R','b','d','Q','f'])
    grammar.append(['T','U','V','U'])
    grammar.append(['T','U'])
    grammar.append(['V','t'])
    grammar.append(['V','u'])
    grammar.append(['U','U','W','X'])
    grammar.append(['U','X'])
    grammar.append(['W','w'])
    grammar.append(['W','x'])
    grammar.append(['X','X','y','Y'])
    grammar.append(['X','Y'])
    grammar.append(['Y','i','Q','j'])
    grammar.append(['Y','R'])
    grammar.append(['Y','Z'])
    grammar.append(['Y','e'])
    grammar.append(['Z','b','i','Á','j'])
    grammar.append(['Á','Ḃ'])
    grammar.append(['Á',''])
    grammar.append(['Ḃ','Ḃ','k','Q'])
    grammar.append(['Ḃ','Q'])
    grammar.remove([])
    return grammar


